# Kind config for kind 1.18 and 1.19 node images. Use
# make/config/kind/config_etcd_no_fsync.yaml for newer versions of kind as they
# support --unsafe-no-fsync etcd flag, which improves test speed.
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
nodes:
  - role: control-plane
